# Generated by Django 3.1.1 on 2020-11-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type1', models.CharField(max_length=20)),
                ('type2', models.CharField(max_length=20)),
                ('hp', models.IntegerField()),
                ('trainers', models.ManyToManyField(blank=True, to='ViewPokedex.Trainer')),
            ],
        ),
    ]
