# Generated by Django 3.1.4 on 2020-12-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20201207_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='desired_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume_upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='seeking_work',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant_skill',
            name='skill_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application_status',
            name='status_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='Job_filled',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_startDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_benefits',
            field=models.CharField(blank=True, max_length=8000),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.CharField(blank=True, max_length=8000),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_requirements',
            field=models.CharField(blank=True, max_length=8000),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_startDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='relocation_package',
            field=models.CharField(blank=True, max_length=8000),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job_application',
            name='application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_offer',
            name='offer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_skill',
            name='required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job_skill',
            name='skill_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='company_description',
            field=models.CharField(blank=True, max_length=8000),
        ),
        migrations.AlterField(
            model_name='organization',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='sector',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school_experience',
            name='GPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='school_experience',
            name='description',
            field=models.CharField(blank=True, max_length=8000),
        ),
        migrations.AlterField(
            model_name='school_experience',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school_experience',
            name='major',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='school_experience',
            name='minor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='school_experience',
            name='school_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='school_experience',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='experience_description',
            field=models.CharField(blank=True, max_length=8000),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
