from django.db import models

# Create your models here.
class Organization(models.Model):
    organization_id  = models.AutoField(primary_key = True)
    company_name = models.CharField(max_length=100)
    company_description = models.CharField(max_length = 8000)
    email = models.CharField(max_length=320)
    phone = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    sector = models.CharField(max_length=50)
    size  = models.IntegerField()
    video_link = models.URLField()

    def __str__(self):
        return(self.company_name)

class Job(models.Model):
    job_id  = models.AutoField(primary_key = True)
    job_title  = models.CharField(max_length=200)
    salary = models.DecimalField(max_digits=12,decimal_places=2)
    apply_startDate  = models.DateField()
    apply_endDate  = models.DateField()
    job_startDate  = models.DateField()
    job_location  = models.CharField(max_length=50)
    job_description  = models.CharField(max_length=8000)
    job_requirements  = models.CharField(max_length=8000)
    relocation_package  = models.CharField(max_length=8000)
    job_benefits  = models.CharField(max_length=8000)
    Job_filled  = models.BooleanField()
    organization_id = models.ForeignKey(Organization, on_delete=models.DO_NOTHING)

    def __str__(self):
        return(self.job_title)
class Applicant(models.Model):
    user_id  = models.AutoField(primary_key = True)
    password  = models.CharField(max_length=50)
    first_name  = models.CharField(max_length=50)
    last_name  = models.CharField(max_length=50)
    desired_title  = models.CharField(max_length=50)
    city  = models.CharField(max_length=50)
    state  = models.CharField(max_length=50)
    email = models.EmailField(max_length=320)
    phone  = models.CharField(max_length=50)
    video_link = models.URLField()
    resume_upload  = models.FileField()
    seeking_work = models.BooleanField()

    def __str__(self):
        return(self.first_name + ' ' + self.last_name)

class Job_Offer(models.Model):
    job_id = models.ForeignKey(Job, on_delete=models.DO_NOTHING, unique=False)
    user_id = models.ForeignKey(Applicant, on_delete=models.DO_NOTHING)
    offer_date  = models.DateField()

    class Meta: #CPK
        unique_together = ('job_id', 'user_id') # FIXME weird quotes

    def __str__(self):
        return(f"Job ID: {self.job_id}\nUser ID: {self.user_id}")

# This class does NOT have an autogenerated id
class Application_Status(models.Model):
    application_status_id = models.IntegerField(primary_key = True)
    status_name  = models.CharField(max_length=50)

    def __str__(self):
        return(self.status_name)

class Job_Application(models.Model):
    user_id = models.ForeignKey(Applicant, on_delete=models.DO_NOTHING)
    job_id = models.ForeignKey(Job, on_delete=models.DO_NOTHING)
    application_date  = models.DateField()
    application_status_id = models.ForeignKey(Application_Status, on_delete=models.DO_NOTHING)
    class Meta: #CPK
        unique_together = ('job_id', 'user_id')
    
    def __str__(self):
        return('Job Application object')
        




class Work_Experience(models.Model):
    work_exp_id  = models.AutoField(primary_key = True)
    job_title   = models.CharField(max_length=200)
    company_name  = models.CharField(max_length=100)
    startDate  = models.DateField()
    endDate  = models.DateField()
    experience_description  = models.CharField(max_length=8000)
    user_id = models.ForeignKey(Applicant, on_delete=models.DO_NOTHING)

    def __str__(self):
        return(self.company_name)


class School_Experience(models.Model):
    school_exp_id  = models.AutoField(primary_key = True)
    major  = models.CharField(max_length=50)
    minor  = models.CharField(max_length=50)
    school_name  = models.CharField(max_length=100)
    GPA = models.DecimalField(max_digits=10,decimal_places=2)
    startDate  = models.DateField()
    endDate  = models.DateField()
    description  = models.CharField(max_length=8000)
    user_id = models.ForeignKey(Applicant, on_delete=models.DO_NOTHING)
    def __str__(self):
        return(self.school_name)


class Skill(models.Model):
    skill_name = models.CharField(primary_key = True, max_length = 50)

    def __str__(self):
        return(self.skill_name)

class Applicant_Skill(models.Model):
    skill_name = models.ForeignKey(Skill, on_delete=models.DO_NOTHING)
    user_id = models.ForeignKey(Applicant, on_delete=models.DO_NOTHING)
    skill_level  = models.IntegerField()
    class Meta: #CPK
        unique_together = ('skill_name', 'user_id')
        
    def __str__(self):
        return('Applicant Skill object')


class Job_Skill(models.Model):
    skill_name = models.ForeignKey(Skill, on_delete=models.DO_NOTHING)
    job_id = models.ForeignKey(Job, on_delete=models.DO_NOTHING)
    skill_level = models.IntegerField()
    required = models.BooleanField()
    class Meta: #CPK
        unique_together = ('skill_name', 'job_id')
        

    def __str__(self):
        return('job_skill object')